#!/bin/bash

set -e
set -o pipefail

trap 'trap - SIGTERM && kill 0' SIGINT SIGTERM EXIT

npx nodemon -e js,jsx,ts,tsx,png,jpg,babelrc,json --watch src --watch . --ignore dist --exec 'npm run react-build; npm run lint-fix' &
npx nodemon --watch webpack.config.js --exec 'npx webpack serve'
