#!/bin/bash

set -e
set -o pipefail

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

npx nodemon -e js,jsx,ts,tsx,png,jpg,babelrc,json --watch src --watch . --exec 'npm run react-build; npm run lint-fix' &
npx webpack serve
